require:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/LineLength:
   Max: 120

RSpec/NestedGroups:
  Exclude:
    - spec/**/*

RSpec/ExampleLength:
  Exclude:
    - spec/**/*

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - given

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Max: 40

RSpec:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: False

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/EmptyFile:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false


Style/ClassAndModuleChildren:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/CaseEquality:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

Naming/MethodName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SymbolProc:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Metrics/ModuleLength:
  Exclude: ["lib/remap/state/extension.rb"]

Lint/ShadowedException:
  Enabled: false

Lint/Void:
  Exclude: ["spec/unit/remap/state/extension_spec.rb"]

Style/SymbolArray:
  EnforcedStyle: brackets

Naming/PredicateName:
  Exclude: ["lib/remap/result.rb"]

Lint/EmptyClass:
  Exclude: ["lib/remap/nothing.rb"]

Style/MixinUsage:
  Enabled: false
